attributes: 
  metadata: 
    label: "Trove Service" 
    weight: 90
    db_password:
      generator: "password"
    user_password:
      generator: "password"
    rabbit_password:
      generator: "password"
    rabbit_user: "trove"
