attributes:
  metadata:
    # Settings group can be one of "general", "security", "compute", "network",
    # "storage", "logging", "openstack_services" and "other".
    group: 'openstack_services'
    label: "Trove Settings"

  auth_name:
    value: ''
    label: 'Auth Username'
    description: ''
    weight: 20
    type: "text"
    regex:
      source: '^[\S]{4,}$'
      error: "Username length should not be less than 4 characters"
    restrictions:
      - action: hide
        condition: settings:fuel-plugin-dbaas-trove.metadata.enabled == false

  auth_password:
    label: 'Auth Password'
    description: ''
    weight: 21
    type: 'password'
    value:
      generator: "password"
    regex:
      source: '^[\S]{8,}$'
      error: "Password length should not be less than 8 characters"
    restrictions:
      - action: hide
        condition: settings:fuel-plugin-dbaas-trove.metadata.enabled == false

  db_password:
    label: 'Database Password'
    description: ''
    weight: 22
    type: 'password'
    value:
      generator: "password"
    regex:
      source: '^[\S]{8,}$'
      error: "Password length should not be less than 8 characters"
    restrictions:
      - action: hide
        condition: settings:fuel-plugin-dbaas-trove.metadata.enabled == false

  rabbit_user:
    label: 'RabbitMQ Username'
    description: ''
    weight: 23
    type: 'text'
    value: ''
    regex:
      source: '^[\S]{4,}$'
      error: "Username length should not be less than 4 characters"
    restrictions:
      - action: hide
        condition: settings:fuel-plugin-dbaas-trove.metadata.enabled == false

  rabbit_password:
    label: 'RabbitMQ Password'
    description: ''
    weight: 24
    type: 'password'
    value:
      generator: "password"
    regex:
      source: '^[\S]{8,}$'
      error: "Password length should not be less than 8 characters"
    restrictions:
      - action: hide
        condition: settings:fuel-plugin-dbaas-trove.metadata.enabled == false

  rabbit_port:
    value: ""
    label: "RabbitMQ Port"
    description: ""
    weight: 25
    type: "text"
    restrictions:
      - action: hide
        condition: settings:fuel-plugin-dbaas-trove.metadata.enabled == false
    regex:
      source: '^(102[4-9]|10[3-9]\d|1[1-9]\d{2}|[2-9]\d{3}|[1-5]\d{4}|6[0-4]\d{3}|65[0-4]\d{2}|655[0-2]\d|6553[0-5])$'
      error: "Invalid Port, Enter a port between 1024 and 65535"
